.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. luascoin_qt test_luascoin_qt
clean: FORCE
	$(MAKE) -C .. luascoin_qt_clean test_luascoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_luascoin_qt_check
luascoin-qt luascoin-qt.exe: FORCE
	 $(MAKE) -C .. luascoin_qt
